# Generated by Django 5.2.5 on 2025-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='previews', verbose_name='Preview')),
            ],
            options={
                'verbose_name': 'Preview',
                'verbose_name_plural': 'Previews',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('is_stable', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='releases/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.TextField(verbose_name='Site Description')),
                ('site_main_title', models.TextField(verbose_name='Main Title')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('copyright', models.CharField(default='Copyright © 2025 Switype', max_length=200, null=True, verbose_name='Copyright')),
                ('maintenance_mode', models.BooleanField(db_index=True, default=False, verbose_name='Maintenance mode')),
                ('is_main_setting', models.BooleanField(db_index=True, default=False, verbose_name='Main setting')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
